services:
  - type: web
    name: yismake-worku
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_SITE_URL
        value: https://yismake-worku.onrender.com
